from typing import List, Optional

from pydantic import BaseModel, Field


class ExecutionStep(BaseModel):
    """A single discrete task in a technical plan."""

    id: str = Field(description="Short ID (e.g., STEP-1)")
    description: str = Field(description="What needs to be done")
    assigned_to: str = Field(description="Agent responsible (e.g., 'coder')")
    dependencies: List[str] = Field(
        default_factory=list, description="IDs of steps that must complete first"
    )


class TechnicalPlan(BaseModel):
    """The full execution strategy generated by the Planning Agent."""

    title: str = Field(description="A descriptive title for the plan")
    summary: str = Field(description="High-level overview of the proposed solution")
    steps: List[ExecutionStep] = Field(description="Ordered list of execution steps")
    estimated_risk: str = Field(
        default="low", description="Risk assessment (low, medium, high)"
    )
    prd_link: Optional[str] = Field(default=None, description="Link to associated PRD")
